# Generated by Django 3.1 on 2020-08-25 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
